{"cells":[{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":691},"executionInfo":{"elapsed":5596,"status":"ok","timestamp":1642335593612,"user":{"displayName":"Денис Жунтов","photoUrl":"https://lh3.googleusercontent.com/a/default-user=s64","userId":"03398161046237101130"},"user_tz":-300},"id":"uBdT2V74_cxE","outputId":"52826cdd-af0f-4576-e7de-cc3d30bb7c3e"},"outputs":[{"output_type":"stream","name":"stdout","text":["Collecting python-telegram-bot\n","  Downloading python_telegram_bot-13.10-py3-none-any.whl (497 kB)\n","\u001b[K     |████████████████████████████████| 497 kB 4.9 MB/s \n","\u001b[?25hCollecting cachetools==4.2.2\n","  Downloading cachetools-4.2.2-py3-none-any.whl (11 kB)\n","Collecting tornado>=6.1\n","  Downloading tornado-6.1-cp37-cp37m-manylinux2010_x86_64.whl (428 kB)\n","\u001b[K     |████████████████████████████████| 428 kB 67.6 MB/s \n","\u001b[?25hCollecting APScheduler==3.6.3\n","  Downloading APScheduler-3.6.3-py2.py3-none-any.whl (58 kB)\n","\u001b[K     |████████████████████████████████| 58 kB 6.5 MB/s \n","\u001b[?25hRequirement already satisfied: pytz>=2018.6 in /usr/local/lib/python3.7/dist-packages (from python-telegram-bot) (2018.9)\n","Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from python-telegram-bot) (2021.10.8)\n","Requirement already satisfied: setuptools>=0.7 in /usr/local/lib/python3.7/dist-packages (from APScheduler==3.6.3->python-telegram-bot) (57.4.0)\n","Requirement already satisfied: six>=1.4.0 in /usr/local/lib/python3.7/dist-packages (from APScheduler==3.6.3->python-telegram-bot) (1.15.0)\n","Requirement already satisfied: tzlocal>=1.2 in /usr/local/lib/python3.7/dist-packages (from APScheduler==3.6.3->python-telegram-bot) (1.5.1)\n","Installing collected packages: tornado, cachetools, APScheduler, python-telegram-bot\n","  Attempting uninstall: tornado\n","    Found existing installation: tornado 5.1.1\n","    Uninstalling tornado-5.1.1:\n","      Successfully uninstalled tornado-5.1.1\n","  Attempting uninstall: cachetools\n","    Found existing installation: cachetools 4.2.4\n","    Uninstalling cachetools-4.2.4:\n","      Successfully uninstalled cachetools-4.2.4\n","\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n","google-colab 1.0.0 requires tornado~=5.1.0; python_version >= \"3.0\", but you have tornado 6.1 which is incompatible.\u001b[0m\n","Successfully installed APScheduler-3.6.3 cachetools-4.2.2 python-telegram-bot-13.10 tornado-6.1\n"]},{"output_type":"display_data","data":{"application/vnd.colab-display-data+json":{"pip_warning":{"packages":["tornado"]}}},"metadata":{}}],"source":["!pip install python-telegram-bot --upgrade"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":1000},"executionInfo":{"elapsed":10611,"status":"ok","timestamp":1642335613980,"user":{"displayName":"Денис Жунтов","photoUrl":"https://lh3.googleusercontent.com/a/default-user=s64","userId":"03398161046237101130"},"user_tz":-300},"id":"0h438TsJSPk1","outputId":"70aa92a8-de18-4704-86a4-32cdeee24a01"},"outputs":[{"output_type":"stream","name":"stdout","text":["Collecting google-cloud-dialogflow\n","  Downloading google_cloud_dialogflow-2.11.0-py2.py3-none-any.whl (1.3 MB)\n","\u001b[K     |████████████████████████████████| 1.3 MB 5.2 MB/s \n","\u001b[?25hCollecting proto-plus>=1.10.0\n","  Downloading proto_plus-1.19.8-py3-none-any.whl (45 kB)\n","\u001b[K     |████████████████████████████████| 45 kB 3.4 MB/s \n","\u001b[?25hCollecting google-api-core[grpc]<3.0.0dev,>=1.28.0\n","  Downloading google_api_core-2.4.0-py2.py3-none-any.whl (111 kB)\n","\u001b[K     |████████████████████████████████| 111 kB 69.5 MB/s \n","\u001b[?25hRequirement already satisfied: setuptools>=40.3.0 in /usr/local/lib/python3.7/dist-packages (from google-api-core[grpc]<3.0.0dev,>=1.28.0->google-cloud-dialogflow) (57.4.0)\n","Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /usr/local/lib/python3.7/dist-packages (from google-api-core[grpc]<3.0.0dev,>=1.28.0->google-cloud-dialogflow) (2.23.0)\n","Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.52.0 in /usr/local/lib/python3.7/dist-packages (from google-api-core[grpc]<3.0.0dev,>=1.28.0->google-cloud-dialogflow) (1.54.0)\n","Requirement already satisfied: protobuf>=3.12.0 in /usr/local/lib/python3.7/dist-packages (from google-api-core[grpc]<3.0.0dev,>=1.28.0->google-cloud-dialogflow) (3.17.3)\n","Requirement already satisfied: google-auth<3.0dev,>=1.25.0 in /usr/local/lib/python3.7/dist-packages (from google-api-core[grpc]<3.0.0dev,>=1.28.0->google-cloud-dialogflow) (1.35.0)\n","Requirement already satisfied: grpcio<2.0dev,>=1.33.2 in /usr/local/lib/python3.7/dist-packages (from google-api-core[grpc]<3.0.0dev,>=1.28.0->google-cloud-dialogflow) (1.43.0)\n","Collecting grpcio-status<2.0dev,>=1.33.2\n","  Downloading grpcio_status-1.43.0-py3-none-any.whl (10.0 kB)\n","Requirement already satisfied: cachetools<5.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from google-auth<3.0dev,>=1.25.0->google-api-core[grpc]<3.0.0dev,>=1.28.0->google-cloud-dialogflow) (4.2.2)\n","Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.7/dist-packages (from google-auth<3.0dev,>=1.25.0->google-api-core[grpc]<3.0.0dev,>=1.28.0->google-cloud-dialogflow) (4.8)\n","Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from google-auth<3.0dev,>=1.25.0->google-api-core[grpc]<3.0.0dev,>=1.28.0->google-cloud-dialogflow) (1.15.0)\n","Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.7/dist-packages (from google-auth<3.0dev,>=1.25.0->google-api-core[grpc]<3.0.0dev,>=1.28.0->google-cloud-dialogflow) (0.2.8)\n","Collecting protobuf>=3.12.0\n","  Downloading protobuf-3.19.3-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)\n","\u001b[K     |████████████████████████████████| 1.1 MB 52.7 MB/s \n","\u001b[?25hRequirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.7/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0dev,>=1.25.0->google-api-core[grpc]<3.0.0dev,>=1.28.0->google-cloud-dialogflow) (0.4.8)\n","Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<3.0.0dev,>=1.28.0->google-cloud-dialogflow) (1.24.3)\n","Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<3.0.0dev,>=1.28.0->google-cloud-dialogflow) (3.0.4)\n","Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<3.0.0dev,>=1.28.0->google-cloud-dialogflow) (2.10)\n","Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<3.0.0dev,>=1.28.0->google-cloud-dialogflow) (2021.10.8)\n","Installing collected packages: protobuf, grpcio-status, google-api-core, proto-plus, google-cloud-dialogflow\n","  Attempting uninstall: protobuf\n","    Found existing installation: protobuf 3.17.3\n","    Uninstalling protobuf-3.17.3:\n","      Successfully uninstalled protobuf-3.17.3\n","  Attempting uninstall: google-api-core\n","    Found existing installation: google-api-core 1.26.3\n","    Uninstalling google-api-core-1.26.3:\n","      Successfully uninstalled google-api-core-1.26.3\n","\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n","google-cloud-translate 1.5.0 requires google-api-core[grpc]<2.0.0dev,>=1.6.0, but you have google-api-core 2.4.0 which is incompatible.\n","google-cloud-language 1.2.0 requires google-api-core[grpc]<2.0.0dev,>=1.6.0, but you have google-api-core 2.4.0 which is incompatible.\n","google-cloud-firestore 1.7.0 requires google-api-core[grpc]<2.0.0dev,>=1.14.0, but you have google-api-core 2.4.0 which is incompatible.\n","google-cloud-datastore 1.8.0 requires google-api-core[grpc]<2.0.0dev,>=1.6.0, but you have google-api-core 2.4.0 which is incompatible.\n","google-cloud-core 1.0.3 requires google-api-core<2.0.0dev,>=1.14.0, but you have google-api-core 2.4.0 which is incompatible.\n","google-cloud-bigquery-storage 1.1.0 requires google-api-core[grpc]<2.0.0dev,>=1.14.0, but you have google-api-core 2.4.0 which is incompatible.\n","google-api-python-client 1.12.8 requires google-api-core<2dev,>=1.21.0, but you have google-api-core 2.4.0 which is incompatible.\n","firebase-admin 4.4.0 requires google-api-core[grpc]<2.0.0dev,>=1.14.0; platform_python_implementation != \"PyPy\", but you have google-api-core 2.4.0 which is incompatible.\u001b[0m\n","Successfully installed google-api-core-2.4.0 google-cloud-dialogflow-2.11.0 grpcio-status-1.43.0 proto-plus-1.19.8 protobuf-3.19.3\n"]},{"output_type":"display_data","data":{"application/vnd.colab-display-data+json":{"pip_warning":{"packages":["google"]}}},"metadata":{}}],"source":["!pip install google-cloud-dialogflow"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"xJ6YALNM_kz3"},"outputs":[],"source":["import os\n","import logging\n","\n","from telegram import Update\n","from telegram.ext import Updater, CommandHandler, MessageHandler, Filters, CallbackContext\n","\n","from google.cloud import dialogflow"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"_VImAIl8_nNX"},"outputs":[],"source":["# Define a few command handlers. These usually take the two arguments update and\n","# context. Error handlers also receive the raised TelegramError object in error.\n","def start(update: Update, context: CallbackContext):\n","    update.message.reply_text('Hi!')\n","\n","def echo(update: Update, context: CallbackContext):\n","    txt = update.message.text\n","    \n","    update.message.reply_text('Я отвечу тем же! ' + update.message.text)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"R5DjHZ5H_pG0"},"outputs":[],"source":["updater = Updater(\"5000711885:AAEBMPEGppkGzzSQZXqxWMka1-wMQrT3FeU\", use_context=True)\n","dispatcher = updater.dispatcher\n","\n","# on different commands - answer in Telegram\n","dispatcher.add_handler(CommandHandler(\"start\", start))\n","dispatcher.add_handler(MessageHandler(Filters.text & ~Filters.command, echo))\n","\n","# Start the Bot\n","updater.start_polling()\n","updater.idle()"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":15623,"status":"ok","timestamp":1642335678842,"user":{"displayName":"Денис Жунтов","photoUrl":"https://lh3.googleusercontent.com/a/default-user=s64","userId":"03398161046237101130"},"user_tz":-300},"id":"7Ztsb3J_R-sv","outputId":"9ef93014-f35b-4ed5-94e8-56c71c85adbe"},"outputs":[{"output_type":"stream","name":"stdout","text":["Mounted at /content/gdrive\n"]}],"source":["from google.colab import drive\n","drive.mount('/content/gdrive')\n"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"_bcv-wFeSDOD"},"outputs":[],"source":["updater = Updater(\"5000711885:AAEBMPEGppkGzzSQZXqxWMka1-wMQrT3FeU\", use_context=True)  # Токен API к Telegram\n","dispatcher = updater.dispatcher\n","os.environ[\"GOOGLE_APPLICATION_CREDENTIALS\"] = 'newagent-vgiy-2f7c5d6945d7.json'# скачнный JSON\n","\n","\n","DIALOGFLOW_PROJECT_ID = 'newagent-vgiy' #PROJECT ID из DialogFlow \n","DIALOGFLOW_LANGUAGE_CODE = 'ru' # язык\n","SESSION_ID = 'ArtInt_bot'  # ID бота из телеграма"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"-dk9F2yVePFh"},"outputs":[],"source":["def startCommand1(update: Update, context: CallbackContext):\n","    update.message.reply_text('Добрый день!')\n","\n","    \n","def textMessage1(update: Update, context: CallbackContext):\n","    session_client = dialogflow.SessionsClient()\n","    session = session_client.session_path(DIALOGFLOW_PROJECT_ID, SESSION_ID)\n","    \n","    text_input = dialogflow.types.TextInput(text=update.message.text , language_code=DIALOGFLOW_LANGUAGE_CODE)\n","    query_input = dialogflow.types.QueryInput(text=text_input)\n","    \n","    try:\n","        response = session_client.detect_intent(session=session, query_input=query_input)\n","    except InvalidArgument:\n","         raise\n","\n","    text = response.query_result.fulfillment_text\n","    if text:\n","        update.message.reply_text(response.query_result.fulfillment_text)\n","    else:\n","        update.message.reply_text('Что?')"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"XjKbKm5XeQyu"},"outputs":[],"source":["# on different commands - answer in Telegram\n","dispatcher.add_handler(CommandHandler(\"start\", startCommand1))\n","dispatcher.add_handler(MessageHandler(Filters.text & ~Filters.command, textMessage1))"]},{"cell_type":"code","execution_count":14,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"Uvkt9x4Deck-","outputId":"705c4ee0-fded-49af-e799-b0d6cdcbaf09","executionInfo":{"status":"ok","timestamp":1642341153400,"user_tz":-300,"elapsed":3436266,"user":{"displayName":"Денис Жунтов","photoUrl":"https://lh3.googleusercontent.com/a/default-user=s64","userId":"03398161046237101130"}}},"outputs":[{"output_type":"stream","name":"stderr","text":["/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: TelegramDeprecationWarning: The argument `clean` of `start_polling` is deprecated. Please use `drop_pending_updates` instead.\n","  \n","No error handlers are registered, logging exception.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/telegram/ext/dispatcher.py\", line 555, in process_update\n","    handler.handle_update(update, self, check, context)\n","  File \"/usr/local/lib/python3.7/dist-packages/telegram/ext/handler.py\", line 198, in handle_update\n","    return self.callback(update, context)\n","  File \"<ipython-input-12-6222ae7fad1a>\", line 6, in textMessage1\n","    session_client = dialogflow.SessionsClient()\n","  File \"/usr/local/lib/python3.7/dist-packages/google/cloud/dialogflow_v2/services/sessions/client.py\", line 406, in __init__\n","    always_use_jwt_access=True,\n","  File \"/usr/local/lib/python3.7/dist-packages/google/cloud/dialogflow_v2/services/sessions/transports/grpc.py\", line 159, in __init__\n","    always_use_jwt_access=always_use_jwt_access,\n","  File \"/usr/local/lib/python3.7/dist-packages/google/cloud/dialogflow_v2/services/sessions/transports/base.py\", line 110, in __init__\n","    **scopes_kwargs, quota_project_id=quota_project_id\n","  File \"/usr/local/lib/python3.7/dist-packages/google/auth/_default.py\", line 459, in default\n","    credentials, project_id = checker()\n","  File \"/usr/local/lib/python3.7/dist-packages/google/auth/_default.py\", line 222, in _get_explicit_environ_credentials\n","    os.environ[environment_vars.CREDENTIALS]\n","  File \"/usr/local/lib/python3.7/dist-packages/google/auth/_default.py\", line 108, in load_credentials_from_file\n","    \"File {} was not found.\".format(filename)\n","google.auth.exceptions.DefaultCredentialsError: File newagent-vgiy-2f7c5d6945d7.json was not found.\n","No error handlers are registered, logging exception.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/telegram/ext/dispatcher.py\", line 555, in process_update\n","    handler.handle_update(update, self, check, context)\n","  File \"/usr/local/lib/python3.7/dist-packages/telegram/ext/handler.py\", line 198, in handle_update\n","    return self.callback(update, context)\n","  File \"<ipython-input-12-6222ae7fad1a>\", line 6, in textMessage1\n","    session_client = dialogflow.SessionsClient()\n","  File \"/usr/local/lib/python3.7/dist-packages/google/cloud/dialogflow_v2/services/sessions/client.py\", line 406, in __init__\n","    always_use_jwt_access=True,\n","  File \"/usr/local/lib/python3.7/dist-packages/google/cloud/dialogflow_v2/services/sessions/transports/grpc.py\", line 159, in __init__\n","    always_use_jwt_access=always_use_jwt_access,\n","  File \"/usr/local/lib/python3.7/dist-packages/google/cloud/dialogflow_v2/services/sessions/transports/base.py\", line 110, in __init__\n","    **scopes_kwargs, quota_project_id=quota_project_id\n","  File \"/usr/local/lib/python3.7/dist-packages/google/auth/_default.py\", line 459, in default\n","    credentials, project_id = checker()\n","  File \"/usr/local/lib/python3.7/dist-packages/google/auth/_default.py\", line 222, in _get_explicit_environ_credentials\n","    os.environ[environment_vars.CREDENTIALS]\n","  File \"/usr/local/lib/python3.7/dist-packages/google/auth/_default.py\", line 108, in load_credentials_from_file\n","    \"File {} was not found.\".format(filename)\n","google.auth.exceptions.DefaultCredentialsError: File newagent-vgiy-2f7c5d6945d7.json was not found.\n","No error handlers are registered, logging exception.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/telegram/ext/dispatcher.py\", line 555, in process_update\n","    handler.handle_update(update, self, check, context)\n","  File \"/usr/local/lib/python3.7/dist-packages/telegram/ext/handler.py\", line 198, in handle_update\n","    return self.callback(update, context)\n","  File \"<ipython-input-12-6222ae7fad1a>\", line 6, in textMessage1\n","    session_client = dialogflow.SessionsClient()\n","  File \"/usr/local/lib/python3.7/dist-packages/google/cloud/dialogflow_v2/services/sessions/client.py\", line 406, in __init__\n","    always_use_jwt_access=True,\n","  File \"/usr/local/lib/python3.7/dist-packages/google/cloud/dialogflow_v2/services/sessions/transports/grpc.py\", line 159, in __init__\n","    always_use_jwt_access=always_use_jwt_access,\n","  File \"/usr/local/lib/python3.7/dist-packages/google/cloud/dialogflow_v2/services/sessions/transports/base.py\", line 110, in __init__\n","    **scopes_kwargs, quota_project_id=quota_project_id\n","  File \"/usr/local/lib/python3.7/dist-packages/google/auth/_default.py\", line 459, in default\n","    credentials, project_id = checker()\n","  File \"/usr/local/lib/python3.7/dist-packages/google/auth/_default.py\", line 222, in _get_explicit_environ_credentials\n","    os.environ[environment_vars.CREDENTIALS]\n","  File \"/usr/local/lib/python3.7/dist-packages/google/auth/_default.py\", line 108, in load_credentials_from_file\n","    \"File {} was not found.\".format(filename)\n","google.auth.exceptions.DefaultCredentialsError: File newagent-vgiy-2f7c5d6945d7.json was not found.\n"]}],"source":["# Хендлеры\n","start_command_handler = CommandHandler('start', startCommand1)\n","text_message_handler = MessageHandler(Filters.text, textMessage1)\n","# Добавляем хендлеры в диспетчер\n","dispatcher.add_handler(start_command_handler)\n","dispatcher.add_handler(text_message_handler)\n","# Начинаем поиск обновлений\n","updater.start_polling(clean=True)\n","# Останавливаем бота, если были нажаты Ctrl + C\n","updater.idle()"]}],"metadata":{"colab":{"collapsed_sections":[],"name":"bot_install_test.ipynb","provenance":[],"authorship_tag":"ABX9TyPI7ptIjBX3WDslyqgBxBTk"},"kernelspec":{"display_name":"Python 3","name":"python3"},"language_info":{"name":"python"}},"nbformat":4,"nbformat_minor":0}